### ISSUE TITLE
Bluetooth Raw Commands

### ISSUE THREAD

**Issue by moe-the-fabber** [fetherston/npm-parrot-minidrone#13]
hey fetherston,
i am looking for the bt rawcommands because
java makes no sense to me ^^. Id like to send
some commands directly to the drone from my
arduino uno. Is that possible in some way?

**Comment by fetherston** [comment]
You'd have to get a bluetooth module for your Arduino and write the file buffers directly to the drone over bluetooth similar to how this library does. I'm not sure what programming languages you can use on arduino though.

**Comment by fetherston** [comment]
These docs are most helpful for writing the BTLE commands: https://github.com/Parrot-Developers/arsdk-xml/blob/master/xml/minidrone.xml

**Comment by moe-the-fabber** [comment]
thank you for answering,
i have set up and arduino with an BTLE device and am able to connect to 
the drone without a handshake or anything. Arduino uses C /++.
I calculated the take off command into "real numbers",out of your code,
wich I then sent direcetly to the drone, but unfortunately nothing happend. 
For takeoff:
"64000, 64011, 4, 64011, 2, 0, 1, 0"
Also tried to sent the handshake first but i guess its not needed?
Do I miss something?

regards moe
