### ISSUE TITLE
How to get the picture ?

### ISSUE THREAD

**Issue by alexandrevilain** [fetherston/npm-parrot-minidrone#5]
Hello, 
I'm trying to get the picture taken during flight with my airbone.

Is it possibile ?

Thanks, 
Alexandre.

**Comment by fetherston** [comment]
It's possible via the Noble Bluetooth library but currently unimplemented in this library.

**Comment by alexandrevilain** [comment]
Thank's for your answer 👍 
Do you have any documentation link ? I'll try to implement this.

**Comment by fetherston** [comment]
Thanks for picking this up, if you can manage to add this it would be a huge contribution! I've primarily used these sources to patch together this library:

[The noble docs](https://github.com/sandeepmistry/noble)
[The Parrot ARSDK PDF](http://developer.parrot.com/docs/SDK3/ARSDK_Protocols.pdf)
[The Parrot Dev Forum](http://forum.developer.parrot.com/)
[The Minidrone command XML file](https://github.com/Parrot-Developers/arsdk-xml/blob/master/xml/minidrone.xml)

To get this to work you will have to implement these commands outlined in the [xml doc here](https://github.com/Parrot-Developers/arsdk-xml/blob/master/xml/minidrone.xml#L226-L320). Testing will be slow going, as the tiny little image is transferred over Bluetooth which takes forever.

**Comment by fetherston** [comment]
Also note the take picture command is already implemented: http://fetherston.github.io/npm-parrot-minidrone/Drone.html

**Comment by alexandrevilain** [comment]
Ok, thanks ! Regarding to the links, It looks to be complicated to get pictures.
